name: CI (Build, Test, JaCoCo)

on:
  push:
  pull_request:

permissions:
  contents: read
  checks: write
  pull-requests: write

jobs:
  build-test-coverage:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Validate Gradle Wrapper
        uses: gradle/actions/wrapper-validation@v4

      - name: Set up JDK 21 (Temurin)
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'

      - name: Setup Gradle (cache)
        uses: gradle/actions/setup-gradle@v4

      - name: Build, Test & Coverage
        run: ./gradlew --no-daemon clean build jacocoTestReport --stacktrace

      - name: Debug JaCoCo report
        if: always()
        run: |
          echo "Listing potential JaCoCo report dirs..."
          ls -lah **/build/reports/jacoco/test || true
          echo
          echo "Showing first lines of found XML files..."
          for f in $(ls **/build/reports/jacoco/test/jacocoTestReport.xml 2>/dev/null); do
            echo "Found: $f"
            head -n 20 "$f" || true
            echo
          done

      - name: Publish JUnit test results
        uses: mikepenz/action-junit-report@v4
        if: always()
        with:
          report_paths: '**/build/test-results/test/TEST-*.xml'
          require_tests: true

      # 🔽🔽 LEGGES INN HER: konverter JaCoCo → Cobertura før CodeCoverageSummary 🔽🔽
      - name: Setup .NET (for ReportGenerator)
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.x

      - name: Convert JaCoCo XML -> Cobertura XML
        uses: danielpalme/ReportGenerator-GitHub-Action@5.4.12
        with:
          reports: '**/build/reports/jacoco/test/jacocoTestReport.xml'  # input (JaCoCo)
          targetdir: 'coverage-converted'                               # output folder
          reporttypes: 'Cobertura'                                      # creates coverage-converted/Cobertura.xml
      # 🔼🔼 SLUTT KONVERTERING 🔼🔼

      - name: Generate coverage summary (markdown + badge)
        uses: irongut/CodeCoverageSummary@v1.3.0
        with:
          filename: 'coverage-converted/Cobertura.xml'  # <- Viktig: bruk Cobertura.xml
          badge: true
          fail_below_min: false
          format: markdown
          hide_branch_rate: false
          hide_complexity: true
          indicators: true
          output: both
          thresholds: '60 80'

      - name: Add coverage to job summary
        if: always()
        run: |
          echo "## Code coverage" >> "$GITHUB_STEP_SUMMARY"
          if [ -f code-coverage-results.md ]; then
            cat code-coverage-results.md >> "$GITHUB_STEP_SUMMARY"
          else
            echo "_No coverage summary file found. Check conversion (Cobertura.xml) step._" >> "$GITHUB_STEP_SUMMARY"
          fi

      - name: Jacoco coverage summary comment (PR)
        uses: madrapps/jacoco-report@v1.6.1
        if: github.event_name == 'pull_request'
        with:
          paths: |
            **/build/reports/jacoco/test/jacocoTestReport.xml  # madrapps leser JaCoCo direkte (behold)
          token: ${{ secrets.GITHUB_TOKEN }}
          title: 'JaCoCo Coverage'
          min-coverage-overall: 0
          min-coverage-changed-files: 0

      - name: Upload test & coverage HTML reports
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: test-and-coverage-reports
          path: |
            **/build/reports/tests/test
            **/build/reports/jacoco/test/html
            coverage-converted/Cobertura.xml
            code-coverage-results.md
