name: CI (Build, Test, JaCoCo)

on:
  push:
  pull_request:

jobs:
  build-test-coverage:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Setup Gradle (cache)
        uses: gradle/actions/setup-gradle@v4

      - name: Build, Test & Coverage
        run: ./gradlew clean build jacocoTestReport --stacktrace

      - name: Publish JUnit test results
        uses: mikepenz/action-junit-report@v4
        if: always()
        with:
          report_paths: '**/build/test-results/test/TEST-*.xml'
          require_tests: true

      - name: Generate coverage summary
        uses: irongut/CodeCoverageSummary@v1.3.0
        with:
          filename: build/reports/jacoco/test/jacocoTestReport.xml
          badge: true
          fail_below_min: false
          format: markdown
          hide_branch_rate: false
          hide_complexity: true
          indicators: true
          output: both
          thresholds: '60 80'

      - name: Add coverage to job summary
        if: always()
        run: |
          echo "## Code coverage" >> "$GITHUB_STEP_SUMMARY"
          if [ -f code-coverage-results.md ]; then
            cat code-coverage-results.md >> "$GITHUB_STEP_SUMMARY"
          else
            echo "_No coverage summary file found. Check that build/reports/jacoco/test/jacocoTestReport.xml exists._" >> "$GITHUB_STEP_SUMMARY"
          fi

      - name: Jacoco coverage summary comment
        uses: madrapps/jacoco-report@v1.6.1
        if: github.event_name == 'pull_request'
        with:
          paths: |
            build/reports/jacoco/test/jacocoTestReport.xml
          token: ${{ secrets.GITHUB_TOKEN }}
          title: 'JaCoCo Coverage'
          min-coverage-overall: 0
          min-coverage-changed-files: 0

      - name: Upload test & coverage HTML reports
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: test-and-coverage-reports
          path: |
            build/reports/tests/test
            build/reports/jacoco/test/html
