name: CI (Build, Test, JaCoCo)

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build-test-coverage:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write   # trengs for PR-kommentar (coverage summary)

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Setup Gradle (cache)
        uses: gradle/actions/setup-gradle@v4

      - name: Build, Test & Coverage
        run: ./gradlew clean build jacocoTestReport --stacktrace

      - name: Publish JUnit test results
        uses: mikepenz/action-junit-report@v4
        if: always()
        with:
          report_paths: '**/build/test-results/test/TEST-*.xml'
          require_tests: true

      - name: Jacoco coverage summary comment
        uses: madrapps/jacoco-report@v1.6.1
        if: github.event_name == 'pull_request'
        with:
          paths: |
            **/build/reports/jacoco/test/jacocoTestReport.xml
          token: ${{ secrets.GITHUB_TOKEN }}
          title: 'JaCoCo Coverage'
          min-coverage-overall: 0
          min-coverage-changed-files: 0

      - name: Upload test & coverage HTML reports
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: test-and-coverage-reports
          path: |
            **/build/reports/tests/test
            **/build/reports/jacoco/test/html
