
name: CI (Build, Test, SonarCloud)

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build-and-analyze:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
      id-token: write   # anbefalt av SonarCloud

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0   # nødvendig for PR-analyse

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Setup Gradle (med cache)
        uses: gradle/actions/setup-gradle@v4

      - name: Build & Test (genererer JaCoCo XML)
        run: ./gradlew clean build jacocoTestReport --stacktrace

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@v2
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.organization=${{ secrets.SONAR_ORGANIZATION }}
            -Dsonar.projectKey=${{ secrets.SONAR_PROJECT_KEY }}
            -Dsonar.java.binaries=build/classes/java/main
            -Dsonar.coverage.jacoco.xmlReportPaths=build/reports/jacoco/test/jacocoTestReport.xml
      # Valgfritt: last opp HTML-rapporter som artefakt
      - name: Upload test & coverage reports
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: test-and-coverage-reports
          path: |
            build/reports/tests/test
            build/reports/jacoco/test/html